### ISSUE TITLE
Clickable handles improvements

### ISSUE THREAD

**Issue by Gann4Life** [Gann4Life/RagdollFactory#2]
Unity has IMGUI elements which can be used for creating handles that manipulate objects.
This will help to create position, rotation and radius handles for the colliders, as well as displaying joint limit handles that are interactable in the editor window.
Plus, it will help with performance as I'm currently manually checking how accurate is the mouse position aiming at each transform (iterating on a loop every frame, what a pain).
It can also save resources because I could stop using the `Repaint()` method.

### TODO
Only in *select* mode.
- [x] Position handles for colliders 
- [ ] Rotation handles for colliders
- [ ] Length handle for colliders
- [ ] Radio handle for capsule colliders
- [x] Limit handles for joints
- [ ] Mass handle for rigidbodies
